// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywhmlikcxdlxfkuoebol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3aG1saWtjeGRseGZrdW9lYm9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNTAxMzIsImV4cCI6MjA3MjYyNjEzMn0.FIz904zdnU0NRnAoz0Dulx-CfuulnptrjscOAVsSguI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});